import { readFileSync } from 'node:fs';
import { JWT } from 'google-auth-library';
import { TEMPLATE_COLUMNS } from '../lib/domain/supplier-template-sheet';
const S = (v: unknown) => String(v ?? '').trim();
const ID = '1V4dqn5e8dtTLjX_wnHx5wOup0arU3TAtsvEvuh0sisY';
const sa = JSON.parse(readFileSync('tmp/firebase-auth/sa.json', 'utf8'));
const jwt = new JWT({ email: sa.client_email, key: sa.private_key, scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'] });
const token = (await jwt.getAccessToken()).token;
const r = await (await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${ID}/values/${encodeURIComponent("'시트1'!A1:BZ1")}?access_token=${token}`)).json();
const have = (r.values?.[0] || []).map(S).filter(Boolean);
const want = TEMPLATE_COLUMNS.map(c => c.name);
console.log(`현재 시트 열 ${have.length}개`);
console.log(`  ${have.join(' | ')}`);
console.log(`\n표준양식 열 ${want.length}개`);
console.log(`  ${want.join(' | ')}`);
const norm = (s: string) => s.replace(/\s/g, '');
const missing = want.filter(w => !have.some(h => norm(h) === norm(w)));
const extra = have.filter(h => !want.some(w => norm(h) === norm(w)));
console.log(`\n★표준에 있는데 이 시트엔 없는 칸 ${missing.length}개`);
console.log(`  ${missing.join(' · ')}`);
console.log(`\n이 시트에만 있는 칸 ${extra.length}개`);
console.log(`  ${extra.join(' · ')}`);
