import assert from 'node:assert/strict';
import { canonicalSalesTabName, pickPublishedSalesTabs, salesPublishedTabIndex, salesTabMatches, NATIVE_MONEY_BLOCK } from '../lib/domain/sales-published-tabs';
import { salesTabForStockTab } from '../lib/domain/sales-block';
assert.equal(canonicalSalesTabName('손오공구독 09.15 10:52'), '오공구독 09.15 10:52');
assert.equal(salesPublishedTabIndex('손오공구독'), 1);
assert.equal(salesTabMatches('손오공구독 09.15', '오공구독'), true);
assert.equal(salesTabMatches('픽업구독 09.15', '오공구독'), false);
assert.deepEqual(pickPublishedSalesTabs(['손오공구독 09.15', '픽업구독 09.15']).map(x => x.prefix), ['오공구독', '픽업구독']);
assert.throws(() => pickPublishedSalesTabs(['손오공구독 09.15', '오공구독 09.15']), /중복/);
assert.equal(salesTabForStockTab('RP012', '구독재고'), '오공구독');
assert.equal(salesTabForStockTab('RP012', '픽업재고'), '픽업구독');
assert.equal(NATIVE_MONEY_BLOCK.오공구독.block.includes('36개월 인수형'), true);
console.log('오공구독 명칭·구형탭 호환·중복 차단·요금블록 9/9 PASS');
