import assert from 'node:assert/strict';
import { canonicalSalesTabName, pickPublishedSalesTabs, salesPublishedTabIndex, salesPublishedTabTitle, salesTabMatches, NATIVE_MONEY_BLOCK } from '../lib/domain/sales-published-tabs';
import { salesTabForStockTab } from '../lib/domain/sales-block';
assert.equal(canonicalSalesTabName('손오공구독 09.15 10:52'), '손오공상품 09.15 10:52');
assert.equal(salesPublishedTabIndex('손오공구독'), 1);
assert.equal(salesTabMatches('손오공구독 09.15', '손오공상품'), true);
assert.equal(salesTabMatches('픽업구독 09.15', '손오공상품'), false);
assert.deepEqual(pickPublishedSalesTabs(['손오공구독 09.15', '픽업구독 09.15']).map(x => x.prefix), ['손오공상품', '픽업구독']);
assert.throws(() => pickPublishedSalesTabs(['손오공구독 09.15', '오공구독 09.15']), /중복/);
assert.equal(salesTabForStockTab('RP012', '구독재고'), '손오공상품');
assert.equal(salesTabForStockTab('RP012', '픽업재고'), '픽업구독');
assert.equal(NATIVE_MONEY_BLOCK.손오공상품.block.includes('36개월 인수형'), true);
assert.equal(salesPublishedTabTitle('상품리스트', 385, '09-21 15:30'), '상품리스트 09-21 15:30 385대');
assert.equal(salesPublishedTabTitle('손오공상품', 59, '09-21 15:30'), '손오공 59대');
assert.equal(salesPublishedTabTitle('픽업구독', 223, '09-21 15:30'), '픽업 223대');
assert.equal(salesPublishedTabTitle('오플구독', 53, '09-21 15:30'), '오플 53대');
console.log('손오공상품 명칭·구형탭 호환·중복 차단·요금블록·탭문패 13/13 PASS');
