import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

/**
 * 기존 hourly-sync의 긴 운영 로직은 그대로 보존하면서,
 * ①~⑤ 최신화가 끝난 직후 / 각 F01 탭 실제 쓰기 직전에 SSOT 게이트를 강제한다.
 *
 * F01은 탭별 소유 공급사가 다르다.
 * - 상품리스트: 이안카·아이언 등 일반 상품 → 여기서는 등록된 SSOT 중 IANKA/IRON을 검증
 * - 오플구독: 오토플러스 전용 → AUTOPLUS를 별도 미리보기/게이트로 검증
 *
 * 소스의 정확한 주입 지점이 바뀌면 조용히 우회하지 않고 이 실행 자체가 실패한다.
 */
const SOURCE = 'scripts/hourly-sync.mts';
const GENERATED = 'scripts/.hourly-sync-ssot.generated.mts';
const MAIN_DUMP = 'tmp/prepublish-main.json';
const OPL_DUMP = 'tmp/prepublish-opl.json';

const mainNeedle = "const p1 = run('⑥ 상품리스트', ['scripts/publish-origin-tab.mts', ...A], /우리 시트 |반영 완료|중단|Error/);";
const oplNeedle = "const p3 = run('⑥ 오플구독', ['scripts/publish-origin-tab.mts', '--only=RP023', '--tab=오플구독', '--at=3', ...A], /반영 완료|중단|Error/);";
const source = readFileSync(SOURCE, 'utf8');
const mainCount = source.split(mainNeedle).length - 1;
const oplCount = source.split(oplNeedle).length - 1;
if (mainCount !== 1 || oplCount !== 1) {
  throw new Error(`SSOT gate 주입 실패: 상품리스트=${mainCount}개, 오플구독=${oplCount}개여야 합니다. 실제 발행을 시작하지 않습니다.`);
}

const guardedMain = `${String.raw`
/* ── MAIN SSOT PREPUBLISH GATE (generated by run-hourly-with-ssot-gate.mts) ── */
const ssotPreview = run('⑥-0 상품리스트 SSOT 발행 미리보기', ['scripts/publish-origin-tab.mts', '--dump=${MAIN_DUMP}'], /우리 시트 |뽑았다|중단|Error/);
if (!ssotPreview.ok) stop('상품리스트 SSOT 발행 미리보기 실패');
const ssotGate = run('⑥-1 상품리스트 SOURCE→ADAPTER→ATOM 게이트', ['scripts/ssot-prepublish-gate.mts', '--dump=${MAIN_DUMP}', '--only=IANKA,IRON'], /SSOT PREPUBLISH (?:PASS|BLOCK)|Error/);
if (!ssotGate.ok) stop('상품리스트 SOURCE→ADAPTER→ATOM 불일치 — F01 반영 차단');
line.push(ssotGate.picked.find((l) => /SSOT PREPUBLISH PASS/.test(l))?.trim() || 'main SSOT gate ok');
/* ── main gate passed: only now may 상품리스트 be written ── */
`}${mainNeedle}`;

const guardedOpl = `${String.raw`
/* ── AUTOPLUS SSOT PREPUBLISH GATE ── */
const ssotOplPreview = run('⑥-2 오플구독 SSOT 발행 미리보기', ['scripts/publish-origin-tab.mts', '--only=RP023', '--tab=오플구독', '--at=3', '--dump=${OPL_DUMP}'], /우리 시트 |뽑았다|중단|Error/);
if (!ssotOplPreview.ok) stop('오플구독 SSOT 발행 미리보기 실패');
const ssotOplGate = run('⑥-3 오플구독 SOURCE→ADAPTER→ATOM 게이트', ['scripts/ssot-prepublish-gate.mts', '--dump=${OPL_DUMP}', '--only=AUTOPLUS'], /SSOT PREPUBLISH (?:PASS|BLOCK)|Error/);
if (!ssotOplGate.ok) stop('오플구독 SOURCE→ADAPTER→ATOM 불일치 — 오플구독 반영 차단');
line.push(ssotOplGate.picked.find((l) => /SSOT PREPUBLISH PASS/.test(l))?.trim() || 'AutoPlus SSOT gate ok');
/* ── AutoPlus gate passed: only now may 오플구독 be written ── */
`}${oplNeedle}`;

const guarded = source
  .replace(mainNeedle, guardedMain)
  .replace(oplNeedle, guardedOpl);

writeFileSync(GENERATED, guarded, 'utf8');

const args = ['tsx', GENERATED, ...process.argv.slice(2)];
const result = spawnSync('npx', args, {
  stdio: 'inherit',
  shell: process.platform === 'win32',
  env: process.env,
});

rmSync(GENERATED, { force: true });
if (result.error) throw result.error;
process.exit(result.status ?? 1);
