import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

/**
 * 기존 hourly-sync의 긴 운영 로직은 그대로 보존하면서,
 * ①~⑤ 최신화가 끝난 직후 / ⑥ F01 실제 쓰기 직전에 SSOT 게이트를 강제한다.
 *
 * 소스의 정확한 주입 지점이 바뀌면 조용히 우회하지 않고 이 실행 자체가 실패한다.
 */
const SOURCE = 'scripts/hourly-sync.mts';
const GENERATED = 'scripts/.hourly-sync-ssot.generated.mts';
const DUMP = 'tmp/prepublish-main.json';

const needle = "const p1 = run('⑥ 상품리스트', ['scripts/publish-origin-tab.mts', ...A], /우리 시트 |반영 완료|중단|Error/);";
const source = readFileSync(SOURCE, 'utf8');
const count = source.split(needle).length - 1;
if (count !== 1) {
  throw new Error(`SSOT gate 주입 실패: ⑥ 상품리스트 발행 지점을 정확히 1개 찾아야 하는데 ${count}개입니다. 실제 발행을 시작하지 않습니다.`);
}

const guarded = `${String.raw`
/* ── SSOT PREPUBLISH GATE (generated by run-hourly-with-ssot-gate.mts) ── */
const ssotPreview = run('⑥-0 SSOT 발행 미리보기', ['scripts/publish-origin-tab.mts', '--dump=${DUMP}'], /우리 시트 |뽑았다|중단|Error/);
if (!ssotPreview.ok) stop('SSOT 발행 미리보기 실패');
const ssotGate = run('⑥-1 SOURCE→ADAPTER→ATOM 게이트', ['scripts/ssot-prepublish-gate.mts', '--dump=${DUMP}'], /SSOT PREPUBLISH (?:PASS|BLOCK)|Error/);
if (!ssotGate.ok) stop('SOURCE→ADAPTER→ATOM 불일치 — F01 반영 차단');
line.push(ssotGate.picked.find((l) => /SSOT PREPUBLISH PASS/.test(l))?.trim() || 'SSOT gate ok');
/* ── gate passed: only now may F01 be written ── */
`}${needle}`;

writeFileSync(GENERATED, source.replace(needle, guarded), 'utf8');

const args = ['tsx', GENERATED, ...process.argv.slice(2)];
const result = spawnSync('npx', args, {
  stdio: 'inherit',
  shell: process.platform === 'win32',
  env: process.env,
});

rmSync(GENERATED, { force: true });
if (result.error) throw result.error;
process.exit(result.status ?? 1);
