import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripDetachedEsignAppendices } from '../lib/domain/esign-document-boundary';

const template = readFileSync('public/contract-template/rental-contract.html', 'utf8');
const mainContract = stripDetachedEsignAppendices(template);
const signPage = readFileSync('app/sign/[token]/page.tsx', 'utf8');
const server = readFileSync('lib/server/freepass-esign.ts', 'utf8');
const documentBuilder = readFileSync('lib/server/freepass-esign-document.ts', 'utf8');
const sharedHtmlBuilder = readFileSync('lib/server/freepass-contract-html.ts', 'utf8');
const reviewRenderer = readFileSync('scripts/render-freepass-standard-contract-review.mts', 'utf8');
const documentPreview = readFileSync('app/esign/preview/[contractCode]/page.tsx', 'utf8');
const publicDocument = readFileSync('app/api/freepass-esign/public/[token]/document/route.ts', 'utf8');
const submissionValidator = readFileSync('lib/server/freepass-esign-submission.ts', 'utf8');
const contractPane = readFileSync('components/FreepassEsignPanes.tsx', 'utf8');
const agreementText = readFileSync('lib/domain/esign-agreement-text.ts', 'utf8');

assert.match(template, /부속서류 1 · 차량 인수증/);
assert.doesNotMatch(mainContract, /부속서류 1 · 차량 인수증/);
assert.doesNotMatch(mainContract, /부속서류 2 · 임대차 계약 사실확인서/);
assert.doesNotMatch(mainContract, /부속서류 3 · 운전자격 검증 확인서/);
assert.doesNotMatch(mainContract, /부속서류 4 · 개인정보/);
assert.doesNotMatch(mainContract, /부속서류 5 · 개인신용정보/);
assert.doesNotMatch(mainContract, /부속서류 6 · 위치정보/);
assert.doesNotMatch(mainContract, /부속서류 7 · 자동이체\(CMS\)/);
assert.match(template, /별도 계약 · 연대보증 약정서/);
assert.doesNotMatch(mainContract, /별도 계약 · 연대보증 약정서/);
assert.doesNotMatch(mainContract, /연대보증인 정보/);
assert.match(mainContract, /data-contract-option="driver"/);
assert.match(mainContract, /data-contract-option="guarantor"/);
assert.match(mainContract, /k==='special_terms'[\s\S]*?setDom\(k,'없음'\)/);
assert.match(mainContract, /\.special-terms-value\.is-empty\{min-height:0/);
assert.match(mainContract, /if\(k==='special_terms'\) e\.classList\.toggle\('is-empty'/);
assert.match(mainContract, /class="special-terms-value" data-field="special_terms">없음</);
assert.doesNotMatch(mainContract, /<div class="k">특약 사항<\/div>/);
assert.match(mainContract, /class="empty-contract-option" data-empty="driver"[^>]*>해당 없음</);
assert.match(mainContract, /class="empty-contract-option" data-empty="guarantor"[^>]*>해당 없음</);
assert.match(mainContract, /보증 최고액/);
assert.match(mainContract, /data-contract-page="special-parties"/);
assert.ok(mainContract.indexOf('data-field="driver_age"') < mainContract.indexOf('data-contract-page="special-parties"'));
assert.ok(mainContract.indexOf('data-field="driver_scope"') < mainContract.indexOf('data-contract-page="special-parties"'));
assert.equal((mainContract.match(/data-field="driver_age"/g) || []).length, 1);
assert.equal((mainContract.match(/data-field="driver_scope"/g) || []).length, 1);
assert.ok(mainContract.indexOf('data-contract-option="special-terms"') < mainContract.indexOf('data-contract-option="driver"'));
assert.ok(mainContract.indexOf('data-contract-option="driver"') < mainContract.indexOf('data-contract-option="guarantor"'));
assert.doesNotMatch(template, /partyPage\.style\.display='none'/);
assert.match(documentBuilder, /inlineContractPdfFonts/);
assert.match(documentBuilder, /document\.fonts\.ready/);
assert.match(documentBuilder, /__rebuildTerms/);
assert.match(documentBuilder, /buildFreepassContractHtml/);
assert.match(sharedHtmlBuilder, /rental-contract\.html/);
assert.match(sharedHtmlBuilder, /stripDetachedEsignAppendices/);
assert.match(sharedHtmlBuilder, /\[data-main-exclude=""\]\{display:none!important\}/);
assert.match(template, /class="section" data-contract-option="guarantor"/);
assert.match(reviewRenderer, /buildFreepassContractHtml/);
assert.match(documentPreview, /document\?draft=1&format=pdf/);
assert.match(publicDocument, /buildFrozenFreepassHtml/);
assert.match(publicDocument, /preview/);
assert.match(publicDocument, /download/);
assert.match(publicDocument, /validateFreepassSubmission\(payload, snapshot, \{ requireSignature: false \}\)/);
assert.match(publicDocument, /snapshotWithPrivateSubmission/);
assert.match(publicDocument, /missing: previewMissing/);
assert.match(publicDocument, /매출증빙 주민번호·CMS 계좌 등은 미리보기 스냅샷에 넣지 않는다/);
assert.match(submissionValidator, /Canonical input validation shared by final submit and no-persist contract preview/);
assert.match(signPage, /openFilledContract/);
assert.match(signPage, /document\?format=html/);
assert.match(signPage, /method: 'POST'/);
assert.match(signPage, /window\.__FLOW__=true/);
assert.match(signPage, /srcDoc=\{filledContract\}/);
assert.match(signPage, /if \(!contractSeenAt\) return toast\('작성한 계약서를 먼저 확인해 주세요\.'/);
assert.match(signPage, /if \(!contractConfirmed\) return toast\('계약서 내용이 맞는지 확인에 표시해 주세요\.'/);
assert.match(template, /CONTRACT_FLOW/);
assert.match(template, /body\.contract-flow \.page\{width:auto;height:auto;min-height:0;overflow:visible/);
assert.match(template, /body\.contract-flow \.pagefoot,body\.contract-flow \.rhead\{display:none!important\}/);
assert.match(template, /if\(CONTRACT_FLOW\)\{[\s\S]*?src\.children/);
assert.match(template, /서면 계약서에 서명·기명날인하거나 전자계약/);
assert.match(template, /서면 계약은 당사자가 서명·기명날인한 계약서를 각 1부씩 보관/);
assert.match(template, /임차인 서명·날인/);
assert.doesNotMatch(template, /본인인증 후 서명/);
assert.match(agreementText, /계약의 세칙·통지 및 계약서 교부/);
assert.match(contractPane, /A4 미리보기/);
assert.match(contractPane, /'링크 만들기'/);
// 2026-08-19: 미리보기 URL 은 previewUrl('a4') — /esign/preview/{code}?view=a4&back={basePath}
assert.match(contractPane, /\/esign\/preview\/\$\{encodeURIComponent\(code\)\}\?\$\{params\.toString\(\)\}/);
assert.match(contractPane, /params\.set\('view', 'a4'\)/);
assert.doesNotMatch(signPage.match(/const REQUIRED_CONSENTS[^;]+/)?.[0] || '', /cms/);
assert.doesNotMatch(server.match(/FREEPASS_ESIGN_REQUIRED_CONSENTS[^;]+/)?.[0] || '', /cms/);

console.log('✓ 본계약 문서 경계: 서면·전자 공용 원본, A4 출력·전자서명 분기, 부속서류 분리');
