import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripDetachedEsignAppendices } from '../lib/domain/esign-document-boundary';

const template = readFileSync('public/contract-template/rental-contract.html', 'utf8');
const mainContract = stripDetachedEsignAppendices(template);
const signPage = readFileSync('app/sign/[token]/page.tsx', 'utf8');
const server = readFileSync('lib/server/freepass-esign.ts', 'utf8');
const documentBuilder = readFileSync('lib/server/freepass-esign-document.ts', 'utf8');
const sharedHtmlBuilder = readFileSync('lib/server/freepass-contract-html.ts', 'utf8');
const reviewRenderer = readFileSync('scripts/render-freepass-standard-contract-review.mts', 'utf8');
const documentPreview = readFileSync('app/esign/preview/[contractCode]/page.tsx', 'utf8');
const contractPane = readFileSync('components/FreepassEsignPanes.tsx', 'utf8');
const agreementText = readFileSync('lib/domain/esign-agreement-text.ts', 'utf8');

assert.match(template, /부속서류 1 · 차량 인수증/);
assert.doesNotMatch(mainContract, /부속서류 1 · 차량 인수증/);
assert.doesNotMatch(mainContract, /부속서류 2 · 임대차 계약 사실확인서/);
assert.doesNotMatch(mainContract, /부속서류 3 · 운전자격 검증 확인서/);
assert.doesNotMatch(mainContract, /부속서류 4 · 개인정보/);
assert.doesNotMatch(mainContract, /부속서류 5 · 개인신용정보/);
assert.doesNotMatch(mainContract, /부속서류 6 · 위치정보/);
assert.doesNotMatch(mainContract, /부속서류 7 · 자동이체\(CMS\)/);
assert.match(template, /별도 계약 · 연대보증 약정서/);
assert.doesNotMatch(mainContract, /별도 계약 · 연대보증 약정서/);
assert.doesNotMatch(mainContract, /연대보증인 정보/);
assert.match(mainContract, /data-contract-option="driver"/);
assert.match(mainContract, /data-contract-option="guarantor"/);
assert.match(mainContract, /k==='special_terms'[\s\S]*?setDom\(k,'없음'\)/);
assert.match(mainContract, /\.special-terms-value\.is-empty\{min-height:0/);
assert.match(mainContract, /if\(k==='special_terms'\) e\.classList\.toggle\('is-empty'/);
assert.match(mainContract, /class="special-terms-value" data-field="special_terms">없음</);
assert.doesNotMatch(mainContract, /<div class="k">특약 사항<\/div>/);
assert.match(mainContract, /class="empty-contract-option" data-empty="driver"[^>]*>해당 없음</);
assert.match(mainContract, /class="empty-contract-option" data-empty="guarantor"[^>]*>해당 없음</);
assert.match(mainContract, /보증 최고액/);
assert.match(mainContract, /data-contract-page="special-parties"/);
assert.ok(mainContract.indexOf('data-field="driver_age"') < mainContract.indexOf('data-contract-page="special-parties"'));
assert.ok(mainContract.indexOf('data-field="driver_scope"') < mainContract.indexOf('data-contract-page="special-parties"'));
assert.equal((mainContract.match(/data-field="driver_age"/g) || []).length, 1);
assert.equal((mainContract.match(/data-field="driver_scope"/g) || []).length, 1);
assert.ok(mainContract.indexOf('data-contract-option="special-terms"') < mainContract.indexOf('data-contract-option="driver"'));
assert.ok(mainContract.indexOf('data-contract-option="driver"') < mainContract.indexOf('data-contract-option="guarantor"'));
assert.doesNotMatch(template, /partyPage\.style\.display='none'/);
assert.match(documentBuilder, /inlineContractPdfFonts/);
assert.match(documentBuilder, /document\.fonts\.ready/);
assert.match(documentBuilder, /__rebuildTerms/);
assert.match(documentBuilder, /buildFreepassContractHtml/);
assert.match(sharedHtmlBuilder, /rental-contract\.html/);
assert.match(sharedHtmlBuilder, /stripDetachedEsignAppendices/);
assert.match(sharedHtmlBuilder, /\[data-main-exclude=""\]\{display:none!important\}/);
assert.match(template, /class="section" data-contract-option="guarantor"/);
assert.match(reviewRenderer, /buildFreepassContractHtml/);
assert.match(documentPreview, /document\?draft=1&format=pdf/);
assert.match(template, /서면 계약서에 서명·기명날인하거나 전자계약/);
assert.match(template, /서면 계약은 당사자가 서명·기명날인한 계약서를 각 1부씩 보관/);
assert.match(template, /임차인 서명·날인/);
assert.doesNotMatch(template, /본인인증 후 서명/);
assert.match(agreementText, /계약의 세칙·통지 및 계약서 교부/);
assert.match(contractPane, /A4 계약서 출력/);
assert.match(contractPane, /계약 링크 만들기/);
assert.match(contractPane, /document\?format=pdf&draft=1/);
assert.doesNotMatch(signPage.match(/const REQUIRED_CONSENTS[^;]+/)?.[0] || '', /cms/);
assert.doesNotMatch(server.match(/FREEPASS_ESIGN_REQUIRED_CONSENTS[^;]+/)?.[0] || '', /cms/);

console.log('✓ 본계약 문서 경계: 서면·전자 공용 원본, A4 출력·전자서명 분기, 부속서류 분리');
